blogs/urls.py
from django.urls import path
from .views import PostListView, PostDetailView


app_name = 'blogs'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>/post/', PostDetailView.as_view(), name='single')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blogs.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePagesView, ContactView, AboutView, ServiceView

app_name = 'pages'

urlpatterns = [
    path('', HomePagesView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('service/', ServiceView.as_view(), name='service'),
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


class AutherModel(models.Model):
    full_name = models.CharField(max_length=100, verbose_name=_('full name'))
    image = models.ImageField(upload_to='auther_images/', verbose_name=_('image'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('auther')
        verbose_name_plural = _('authers')


class PostTagModel(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextUploadingField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='main_images/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='post_banners/', verbose_name=_('banner'))
    auther = models.ForeignKey(AutherModel, related_name='posts', on_delete=models.RESTRICT)
    tag = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tag'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')

pages/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import PostModel


class PostListView(ListView):
    template_name = 'gallery.html'

    def get_queryset(self):
        qs = PostModel.objects.order_by('-id')
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs


class PostDetailView(DetailView):
    model = PostModel
    template_name = 'gallery-single.html'

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePagesView(TemplateView):
    template_name = 'index.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class ServiceView(TemplateView):
    template_name = 'services.html'

templates/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>About</h2>
                        <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas
                            consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione
                            sint. Sit quaerat ipsum dolorem.</p>

                        <a class="cta-btn" href="{% url 'pages:contact' %}">Available for hire</a>

                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->

        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container">

                <div class="row gy-4 justify-content-center">
                    <div class="col-lg-4">
                        <img src="{% static 'img/profile-img.jpg' %}" class="img-fluid" alt="">
                    </div>
                    <div class="col-lg-5 content">
                        <h2>Professional Photographer from New York</h2>
                        <p class="fst-italic py-3">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore
                            magna aliqua.
                        </p>
                        <div class="row">
                            <div class="col-lg-6">
                                <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong>
                                        <span>1 May 1995</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>www.example.com</span>
                                    </li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong>
                                        <span>+123 456 7890</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>City:</strong>
                                        <span>New York, USA</span></li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>30</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Master</span>
                                    </li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>email@example.com</span>
                                    </li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong>
                                        <span>Available</span></li>
                                </ul>
                            </div>
                        </div>
                        <p class="py-3">
                            Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt
                            adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
                            Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus
                            itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis
                            culpa magni laudantium dolores.
                        </p>
                        <p class="m-0">
                            Recusandae est praesentium consequatur eos voluptatem. Vitae dolores aliquam itaque odio
                            nihil. Neque ut neque ut quae voluptas. Maxime corporis aut ut ipsum consequatur.
                            Repudiandae sunt sequi minus qui et. Doloribus molestiae officiis.
                            Soluta eligendi fugiat omnis enim. Numquam alias sint possimus eveniet ad. Ratione in earum
                            eum magni totam.
                        </p>
                    </div>
                </div>

            </div>
        </section><!-- End About Section -->

    </main><!-- End #main -->

{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% block content %}

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>Contact</h2>
                        <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas
                            consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione
                            sint. Sit quaerat ipsum dolorem.</p>

                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->

        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container">

                <div class="row gy-4 justify-content-center">

                    <div class="col-lg-3">
                        <div class="info-item d-flex">
                            <i class="bi bi-geo-alt flex-shrink-0"></i>
                            <div>
                                <h4>Location:</h4>
                                <p>Tashkent,Uzbekistan</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="col-lg-3">
                        <div class="info-item d-flex">
                            <i class="bi bi-envelope flex-shrink-0"></i>
                            <div>
                                <h4>Email:</h4>
                                <p>shamsiddintoshpolatov13@gmail.com</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="col-lg-3">
                        <div class="info-item d-flex">
                            <i class="bi bi-phone flex-shrink-0"></i>
                            <div>
                                <h4>Call:</h4>
                                <p>+998 88 038 13 77</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->

                </div>

                <div class="row justify-content-center mt-4">

                    <div class="col-lg-9">
                        <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <input type="text" name="name" class="form-control" id="name"
                                           placeholder="Your Name" required>
                                </div>
                                <div class="col-md-6 form-group mt-3 mt-md-0">
                                    <input type="email" class="form-control" name="email" id="email"
                                           placeholder="Your Email" required>
                                </div>
                            </div>
                            <div class="form-group mt-3">
                                <input type="text" class="form-control" name="subject" id="subject"
                                       placeholder="Subject" required>
                            </div>
                            <div class="form-group mt-3">
                                <textarea class="form-control" name="message" rows="5" placeholder="Message"
                                          required></textarea>
                            </div>
                            <div class="my-3">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Your message has been sent. Thank you!</div>
                            </div>
                            <div class="text-center">
                                <button type="submit">Send Message</button>
                            </div>
                        </form>
                    </div><!-- End Contact Form -->

                </div>

            </div>
        </section><!-- End Contact Section -->

    </main><!-- End #main -->

{% endblock %}

templates/gallery-single.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>Gallery Single</h2>
                        <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas
                            consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione
                            sint. Sit quaerat ipsum dolorem.</p>

                        <a class="cta-btn" href="{% url 'pages:contact' %}">Available for hire</a>

                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->

        <!-- ======= Gallery Single Section ======= -->
        <section id="gallery-single" class="gallery-single">
            <div class="container">

                <div class="position-relative h-100">
                    <div class="slides-1 portfolio-details-slider swiper">
                        <div class="swiper-wrapper align-items-center">

                            <div class="swiper-slide">
                                <img src="{{ object.banner.url }}" alt="{{ object.title }}">
                            </div>

                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>

                </div>

                <div class="row justify-content-between gy-4 mt-4">

                    <div class="col-lg-8">
                        <div class="portfolio-description">
                            <h2>{{ object.title }}</h2>
                            {{ object.body|safe }}

                            <div class="testimonial-item">

                                <div>
                                    <img src="{{ object.auther.image.url }}" class="testimonial-img"
                                         alt="{{ object.auther.full_name }}">
                                    <h3>{{ object.auther.full_name }}</h3>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tag.values %}
                                            <a href="{% url 'blogs:posts' %}?tag={{ tag.name }}">#{{ tag.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="portfolio-info">
                            <h3>Project information</h3>
                            <ul>
                                <li><strong>Category</strong> <span>Nature Photography</span></li>
                                <li><strong>Client</strong> <span>ASU Company</span></li>
                                <li><strong>Project date</strong> <span>{{ object.created_at|date:'F d, Y' }}</span>
                                </li>
                                <li><strong>Project URL</strong> <a href="#">www.example.com</a></li>
                                <li><a href="#" class="btn-visit align-self-start">Visit Website</a></li>
                            </ul>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Gallery Single Section -->

    </main><!-- End #main -->

{% endblock %}

templates/gallery.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
{#                        {% if request.GET %}#}
{#                            <h2>#{{ request.GET.tag }}</h2>#}
{#                        {% else %}#}
                            <h2>Gallery</h2>
{#                        {% endif %}#}
                        <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas
                            consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione
                            sint. Sit quaerat ipsum dolorem.</p>

                        <a class="cta-btn" href="{% url 'pages:contact' %}">Available for hire</a>

                    {% if request.GET %}
                            <h2>#{{ request.GET.tag }}</h2>
                    {% endif %}

                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->

        <!-- ======= Gallery Section ======= -->
        <section id="gallery" class="gallery">
            <div class="container-fluid">

                <div class="row gy-4 justify-content-center">
                    {% for post in object_list %}
                        <div class="col-xl-3 col-lg-4 col-md-6">
                            <div class="gallery-item h-100">
                                <img src="{{ post.main_image.url }}" class="img-fluid" alt="">
                                <div class="gallery-links d-flex align-items-center justify-content-center">
                                    <a href="{{ post.main_image.url }}" title="Gallery 1"
                                       class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>
                                    <a href="{% url 'blogs:single' post.pk %}" class="details-link"><i
                                            class="bi bi-link-45deg"></i></a>
                                </div>
                            </div>
                        </div><!-- End Gallery Item -->
                    {% endfor %}
                </div>

            </div>
        </section><!-- End Gallery Section -->
    </main><!-- End #main -->

{% endblock %}

templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex flex-column justify-content-center align-items-center" data-aos="fade"
             data-aos-delay="1500">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 text-center">
                    <h2>I'm <span>Jenny Wilson</span> a Professional Photographer from New York City</h2>
                    <p>Blanditiis praesentium aliquam illum tempore incidunt debitis dolorem magni est deserunt sed qui
                        libero. Qui voluptas amet.</p>
                    <a href="{% url 'pages:contact' %}" class="btn-get-started">Available for hire</a>
                </div>
            </div>
        </div>
    </section><!-- End Hero Section -->

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= Gallery Section ======= -->
        <section id="gallery" class="gallery">
            <div class="container-fluid">

                <div class="row gy-4 justify-content-center">
                    {% for post in object_list %}
                        <div class="col-xl-3 col-lg-4 col-md-6">
                            <div class="gallery-item h-100">
                                <img src="{{ post.main_image.url }}" class="img-fluid" alt="">
                                <div class="gallery-links d-flex align-items-center justify-content-center">
                                    <a href="{% static 'img/gallery/gallery-1.jpg' %}" title="Gallery 1"
                                       class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>
                                    <a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>
                                </div>
                            </div>
                        </div><!-- End Gallery Item -->
                    {% endfor %}
                </div>

            </div>
        </section><!-- End Gallery Section -->

    </main><!-- End #main -->

{% endblock %}

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>PhotoFolio Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Cardo:ital,wght@0,400;0,700;1,400&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: PhotoFolio - v1.0.0
    * Template URL: https://bootstrapmade.com/photofolio-bootstrap-photography-website-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

{% include 'layouts/navbar.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<div id="preloader">
    <div class="line"></div>
</div>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/layouts/footer.html
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>PhotoFolio</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="#">SHAMS</a>
        </div>
    </div>
</footer>
<!-- End Footer -->

templates/layouts/navbar.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid d-flex align-items-center justify-content-between">

        <a href="{% url 'pages:home' %}" class="logo d-flex align-items-center  me-auto me-lg-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <i class="bi bi-camera"></i>
            <h1>PhotoFolio</h1>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="{% url 'pages:home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a></li>
                <li><a href="{% url 'pages:about' %}"
                       class="{% if request.path == '/about/' %}active{% endif %}">About</a></li>
                <li class="dropdown"><a href="{% url 'blogs:posts' %}"
                                        class="{% if request.path == '/blog/' %}active{% endif %}"><span>Gallery</span>
                    <i class="bi bi-chevron-down dropdown-indicator"></i></a>
{#                    <ul>#}
{#                        <li><a href="">Nature</a></li>#}
{#                        <li><a href="{% url '' %}" class="{% if request.path == '/people/' %}active{% endif %}">People</a></li>#}
{#                        <li><a href="{% url '' %}" class="{% if request.path == '/architecture/' %}active{% endif %}">Architecture</a></li>#}
{#                        <li><a href="{% url '' %}" class="{% if request.path == '/animals/' %}active{% endif %}">Animals</a></li>#}
{#                        <li><a href="{% url '' %}" class="{% if request.path == '/sports/' %}active{% endif %}">Sports</a></li>#}
{#                        <li><a href="{% url '' %}" class="{% if request.path == '/city/' %}active{% endif %}">Cities</a></li>#}
{#                    </ul>#}
                </li>
                <li><a href="{% url 'pages:service' %}"
                       class="{% if request.path == '/service/' %}active{% endif %}">Services</a></li>
                <li><a href="{% url 'pages:contact' %}"
                       class="{% if request.path == '/contact/' %}active{% endif %}">Contact</a></li>
            </ul>
        </nav><!-- .navbar -->

        <div class="header-social-links">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header>
<!-- End Header -->